`define MEM_INIT_G__this_mem_m_0 "test_calcuclator_polling/G__this_mem_m_0.log"
`define MEM_INIT_G__this_mem_m_1 "test_calcuclator_polling/G__this_mem_m_1.log"
`define MEM_INIT_G__this_mem_m_2 "test_calcuclator_polling/G__this_mem_m_2.log"
`define MEM_INIT_G__this_mem_m_3 "test_calcuclator_polling/G__this_mem_m_3.log"
